# Documentation on how to configure the bundle can be found at: https://symfony.com/doc/current/bundles/LiipImagineBundle/basic-usage.html
liip_imagine:
    # valid drivers options include "gd" or "gmagick" or "imagick"
    driver: "gd"
    resolvers:
        # setup the default resolver
        default:
            # use the default web path
            web_path: ~
    filter_sets:
        # use the default cache configuration
        cache: ~
        limit450:
            quality: 75
            filters:
                thumbnail: { size: [ 450, 450 ], mode: outbound }
        limit600:
            quality: 90
            filters:
                thumbnail: { size: [ 600,600 ], mode: outbound }
        watermark:
            filters: 
                watermark_image:
                    image: assets/images/afac_logo_white_watermark.png
                    size: 0.8
                    position: center
        watermark_bottom:
            filters:
                watermark_image:
                    image: assets/images/afac_logo_white_watermark.png
                    size: 0.5
                    position: bottomright

