vich_uploader:
    db_driver: orm

    mappings:
         artist_file:
             uri_prefix: /uploads/images/artists
             upload_destination: '%kernel.project_dir%/public/uploads/images/artists'
             namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
