vich_uploader:
    db_driver: orm

    mappings:
         artist_file:
             uri_prefix: '%upload_artist_directory%'
             upload_destination: '%kernel.project_dir%/public/%upload_artist_directory%'
             namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
