controllers:
    resource: ../src/Controller/
    type: annotation

kernel:
    resource: ../src/Kernel.php
    type: annotation

access_denied:
    path: /403
    controller: App\Controller\ErrorController::accessDenied
